### ISSUE TITLE
[Curious] New Whisper update supports word-level timestamp

### ISSUE THREAD

**Issue by arnavmehta7** [m-bain/whisperX#125]
Whisper uploaded new changes for supporting word-level timestamp and few more changes like tuning of the decoding - https://github.com/openai/whisper/blob/main/CHANGELOG.md . I was wondering if whisperx will still be relevant or not after this change. What is the difference?

**Comment by m-bain** [comment]
thank you for drawing it to my attention, I will update numbers in the arxiv asap.

@arnavmehta7 whisperx still relevant. The drifting, hallucination and repetition of their buffered transcription approach cannot do well on word segmentation. 
Please see paper for details https://arxiv.org/abs/2303.00747

**Comment by koldbrandt** [comment]
Thank you for the update!

**Comment by arnavmehta7** [comment]
> Fyi I ran their new transcribe code with `--word_timestamps True` and get heaps of repetitive text.
> 
> ```
> 00:35:01,640 --> 00:35:01,760
> Yeah, exactly, and just the other comment about whether you<u> want</u> to do both speaker characterization and topic segmentation.
> 
> 6016
> 00:35:01,760 --> 00:35:01,840
> Yeah, exactly, and just the other comment about whether you want<u> to</u> do both speaker characterization and topic segmentation.
> 
> 6017
> 00:35:01,840 --> 00:35:01,960
> Yeah, exactly, and just the other comment about whether you want to<u> do</u> both speaker characterization and topic segmentation.
> 
> ...
> ```
> 
> [openai/whisper#1046](https://github.com/openai/whisper/discussions/1046) So the word segmentation results are even worse than our implementation of attention based whisper word-timestamps.
> 
> Seems its still very much experimental

Around 5 hours ago, IIRC, they pushed something more for fixing hallucinations maybe?

**Comment by m-bain** [comment]
> Thank you for the update! Edit: It seems like after reading the thread that you are linking to that they are about to find a solution. [openai/whisper#1046 (reply in thread)](https://github.com/openai/whisper/discussions/1046#discussioncomment-5235608)

> Around 5 hours ago, IIRC, they pushed something more for fixing hallucinations maybe?

Yes this was running the most recent commit (I pulled an hour ago) :), I think long-form transcription still not fixed

**Comment by arnavmehta7** [comment]
Coool

**Comment by pautri** [comment]
@m-bain this is how they've implemented the word-level segmentation in the srt and vtt files, it's not actually a repetition but each segment contains the whole phrase with a different word highlighted using html "underline". On a test sample of mine I found the word-level timestamps to be quite good actually, often a bit better than whisperx (but not always).

**Comment by m-bain** [comment]
@pautri Ah thanks for pointing that out, okay I reran with their implementation, word segmentation is a bit better but still not matching whisperx level. (see updated table below)

![Screenshot 2023-03-08 at 17 36 12](https://user-images.githubusercontent.com/36994049/223788002-18b0a38d-34ec-4157-88a5-dcb363c9d372.png)

**Comment by WojciechTyczynski** [comment]
> @pautri Ah thanks for pointing that out, I was able to successfully get their word timestamps now. Word segmentation is a bit better but still not matching whisperx level. (see updated table below)
> 
> ![Screenshot 2023-03-08 at 17 36 12](https://user-images.githubusercontent.com/36994049/223788002-18b0a38d-34ec-4157-88a5-dcb363c9d372.png)

@m-bain Is the code you are using for benchmarking available somewhere?

**Comment by haikyuu** [comment]
> Is the code you are using for benchmarking available somewhere?

Good question, in my experiments whisper timestamped is the most precise one in terms of word level precision

**Comment by Jeronymous** [comment]
> Good question, in my experiments whisper timestamped is the most precise one in terms of word level precision

That's also what I see in my experiments.
It would be good to include [whisper-timestamped](https://github.com/linto-ai/whisper-timestamped) in the experiments of the paper, because there is a significant difference in terms of performance with the implementation of OpenAI.
Just the good options have to be set (as described here https://github.com/linto-ai/whisper-timestamped#options-that-may-improve-results)
And the results also vary depending on the openai-whisper version (I personally had good experience with version 20230308 which is not the most recent). Because decoding heuristics are always changing.

Also it would be good to include faster_whisper, which now also can provide word level timestamps and the possibility to run VAD upstream.

**Comment by m-bain** [comment]
@Jeronymous [whisper-timestamped](https://github.com/linto-ai/whisper-timestamped) was used to report Whisper Precision / Recall in the paper [(Table 2)](https://www.robots.ox.ac.uk/~vgg/publications/2023/Bain23/bain23.pdf). I tried several open-source implementations for word level timestamps (stable-ts, openai's, whisper-timestamped) at the time of submission and whisper-timestamped was the best amongst them, but still _below_ whisperx performance.

Of course these repositories have pushed changes since writing the paper, and hence we provide the commit used for the comparison in the paper.

The message of the paper is how to enable batched inference of a single long-form audio file in whisper with word level timestamps. None of the repositories you mention have this functionality and it is not possible with their method. So whilst I could continually update the benchmarks, the message remains the same.

I will work to open-sourcing the benchmark code when I have time (although its fairly trivial to implement), but my focus now is on improving diarization.

**Comment by Jeronymous** [comment]
Thanks for answering and for clarifying.

> Whisper-timestamped have alignment failures meaning some files could not be transcribed.

I am sorry that you experienced this.
Such issues were reported and fixed. No failure has been reported since April 16.

Also note that several improvements were made since the version of Feb 24th that you tested.
Including VAD as an option, which greatly improve accuracy (removing hallucinations), and several improvements in the heuristics to find the best alignment.

> The message of the paper is how to enable batched inference of a single long-form audio file in whisper with word level timestamps. 

Interesting. Do you see a limitation not to do batch inference when the alignment is done with cross-attention weights (instead of an external wav2vec model)?
It is not implemented in openai and whisper-timestamped, but I think it could, just by processing segments from VAD in parallel.
My point of view is that, more than comparing particular implementations, it is relevant to compare in terms of accuracy, efficiency and convenience the three kind of approaches:
* using wav2vec alignment (WhisperX)
* using Whisper cross-attention weights (openai-whisper, faster_whisper, whisper-timestamped)
* using Whisper probabilities of timestamps (whisper.cpp, table-ts... not mentioned in the paper).

> I will work to open-sourcing the benchmark code when I have time, but my focus now is on improving diarization.

Thank you for your work :+1: 
(Indeed diarization and streaming are big added values with respect to original openai-whisper implementation)

A critical part to reproduce the paper is how were Recall & Precision computed exactly.
I opened a few days ago an issue about that: https://github.com/m-bain/whisperX/issues/329

The paper only mentions how the "true positive" are counted, which is kind of the easy part.
But what is done when a target word correspond to several predicted word (for instance)? How are silence segments taken into account exactly?...
I'm discussing this with a colleague and we are imagining several solutions that make sense.
Clarifying this would be super helpful to reproduce the benchmark, with little efforts in comparison with releasing all the benchmark code.
