### ISSUE TITLE
[Code Query] Why are we passing mel of only a particular segment along with the full audio?

### ISSUE THREAD

**Issue by arnavmehta7** [m-bain/whisperX#156]
https://github.com/m-bain/whisperX/blob/main/whisperx/transcribe.py#L333
Over here, as I see, we are passing .transcribe() entire audio but the mel of only a particular segment, I wonder how does it works that way?

**Comment by arnavmehta7** [comment]
@m-bain can you explain please?

**Comment by m-bain** [comment]
Hi, we transcribe the VAD segment independently, as so pass in the mel for each segment. Alternatively, could just pass in the trimmed audio numpy array, and it would produce the log mel spectrogram. But we do it outside the loop here
https://github.com/m-bain/whisperX/blob/9482d324d08c8269dba10969a5b79520a2794001/whisperx/asr.py#L35

Now why do we pass in audio to `transcribe` too? Well its actually not needed since this if statement is never called https://github.com/m-bain/whisperX/blob/9482d324d08c8269dba10969a5b79520a2794001/whisperx/asr.py#L121

 I just did it to keep consistent with whispe'sr definition of 
`def transcribe` for which `audio` is a required argument:

https://github.com/openai/whisper/blob/b5851c6c40e753606765ac45b85b298e3ae9e00d/whisper/transcribe.py#L38

**Comment by arnavmehta7** [comment]
Oh wow, thankyou. I had read the code and realised this few days ago xD but I had forgotten again. Thankyou
