### ISSUE TITLE
[v3] is realy fast. Well done. But word/sentence/segment alignment is off

### ISSUE THREAD

**Issue by dgoryeo** [m-bain/whisperX#224]
Good job with the speed in v3. I had stopped using WhisperX sometime ago because it was too slow for me but this version is remarkable. 

I tried it on several audio files. Things that need improvement in my quick test:

-- Transcriptions come out way way too long sentences bundled to each other. I expect the split to be at punctuation but no many sentences are packed together. I tried with language "ja". May be VAD chunks are too large?

-- Diariaze flag didn't work for me. Nothing as output. 

Thanks

**Comment by sorgfresser** [comment]
The first one is reported in #200 so you might want to refer to it for updates on this.
Could you elaborate the second issue further? Did you specify a huggingface-token? Can you provide a reproducible example?

**Comment by dgoryeo** [comment]
Thanks @sorgfresser . I checked and the json files do speakers. Is there anyway for me to convert that json to an srt or vtt?

**Comment by sorgfresser** [comment]
Not directly since there is no native way to handle speaker information in vtt, srt etc.
What you could do: on diarizing, each of the segments in `result["segments"]` get's a `speaker` key, that you can access with `result["segments"]["speaker"]`. This is passed to the writers specified in utils.py too. As such, you can easily add something like `<speakername>:` at the beginning of each caption-part in your writer of choice.
For example regarding the `write_srt` function, you could rewrite it to
```
    for i, segment in enumerate(transcript, start=1):
        # write srt lines
        print(
            f"{i}\n"
            f"{format_timestamp(segment['start'], always_include_hours=True, decimal_marker=',')} --> "
            f"{format_timestamp(segment['end'], always_include_hours=True, decimal_marker=',')}\n"
            f"{segment["speaker"]}: {segment['text'].strip().replace('-->', '->')}\n",
            file=file,
            flush=True,
        )
```
The same can be done for the other writers. But the owner of this repo is currently changing diarization, so you might have to update this once he's done with it.

**Comment by m-bain** [comment]
try most recent release, it uses nltk sentence tokenization to keep segments short. And `[SPEAKER XX]:` is added to .srt by default now
