### ISSUE TITLE
Output file is empty (WhisperX, Ctranslate2 with Subtitle Edit)(No text found!)(Error identified: Compute type.)

### ISSUE THREAD

**Issue by llurk** [m-bain/whisperX#285]
"I have installed WhisperX to use with Subtitle Edit, but I have one problem. When I use WhisperX with all models, I get an error stating that the text cannot be found. When using the batch function with multiple files, the exported SRT files are all empty. Can anyone help me solve this problem? Furthermore, if I want to use WhisperX with CMD, are there any specific instructions?"
I have installed the environment using Miniconda 3 and the related software, but I don't know how to customize and use CMD to run it for a specific video. Here is the log file of Subtitle Edit. Please help me with this.

[error_log.txt](https://github.com/m-bain/whisperX/files/11600574/error_log.txt)

Here is the log when I use WhisperX with two models, Medium and Large. 

Moreover, this issue only occurs when I use WhisperX with Ctranslate2. Whisper works fine with two engines, const-me and cpp. I have deleted the files related to the OpenAI engine. Although I remember it still working fine, I don't use it because it's too slow. 

 Thank you for taking the time to read and engage with my question.

![image](https://github.com/m-bain/whisperX/assets/134845325/287850f9-5e35-4b7b-a4e2-076b479138b9)

**Comment by oep42** [comment]
This error is in your "error_log.txt":

> ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

According to that error message, "float16 compute type" is not supported by your hardware. In Whisperx's Help, it says this about Whisper's option "compute_type":

> --compute_type {float16,float32,int8}  compute type for computation (default: float16)

This says that there are three possible values for "compute_type", and that "float16" is the default value. So if you don't specify the option "compute_type", WhisperX will use the value "float16". 

According to your "error_log.txt", this is the way that WhisperX is run (on 05/30/2023 20:41:25) from Subtitle Edit:

`whisperx.exe --language en --model "small" "C:\Users\xxx\AppData\Local\Temp\e4adda82-7cf3-4919-b22b-727f2464fc0e.wav"`

Only two options are specified by SE, `--language` and `--model`. Because SE does not specify `--compute_type`, it is impossible for you to use WhisperX from SE, because your hardware doesn't support the default "float16" value of `--compute_type`. (So you could only use WhisperX from SE, if SE would have an option to specify the value of `--compute_type`. As far as I know, SE does not have such an option now.)

Because you cannot use WhisperX from SE, you could try to run WhisperX as Administrator from your command-line interface (i.e. Windows Command Prompt or Windows Powershell, with "Administator" at the top of its window), which looks like in this image from [Purfview](https://github.com/Purfview/whisper-standalone-win):
![68747470733a2f2f692e696d6775722e636f6d2f4459566d3375362e706e67](https://github.com/m-bain/whisperX/assets/84353335/304fc9ae-30c1-4a38-ac8d-9e3bd2f06d68)

For more info about running programs in your command-line interface, see here (as suggested by Purfview): https://youtu.be/A3nwRCV-bTU

The "compute_type" error is discussed [here](https://github.com/m-bain/whisperX/issues/229). A solution that seems to work for many, is to give `--compute_type` the value "int8". You could try to run a command like this in your command-line interface:

`whisperx --language=en --model=medium --output_dir=D:\TestFolder --output_format=srt --compute_type=int8 "D:\TestFolder\TestVideo.mkv"`

If this works, this will result in a SRT file with subtitles. If you create an SRT file in this way, you do not use Subtitle Edit's post-processing for Whisper transcriptions. As a kind of replacement for that, you could use SE's "Tools/Batch convert" option.

For an overview of WhisperX's options, run this command:

`whisperx --help`

**Comment by llurk** [comment]
Okay, I've made it. There's one more thing I want to ask: I want to change the compute type of WhisperX. Is there a settings file, and if so, what is the path? Additionally, if I use the command prompt (cmd), how can I use it with multiple videos?

**Comment by oep42** [comment]
As far as I know, there is no settings file for changing the default compute type of WhisperX. You have to add `--compute_type=int8`, each time you run WhisperX.

The standard way to use WhisperX for multiple videos, is like this (for three videos):

`whisperx --language=en --model=medium --output_dir=D:\TestFolder --output_format=srt --compute_type=int8 "D:\TestFolder\TestVideo1.mp4" "D:\TestFolder\TestVideo2.mp4" "D:\TestFolder\TestVideo3.mp4"`

In my experience, this doesn't work, because there is always an error in the last video, and then no subtitles are produced at all. (This is my experience with WhisperX version 2.0.1. Perhaps I should report this.)

Based on a suggestion from [here](https://github.com/openai/whisper/discussions/153), you could do the following:

(1) Choose a fixed folder that you will only use for transcribing videos. Let's call it `D:\SubFactory`. 

(2) Place some very short test videos in this folder, for a later test run.

(3) Create a text file with the following contents:

```
for %%A in (D:\SubFactory\*.mkv) do (whisperx --language=en --model=tiny --output_dir=D:\SubFactory --output_format=srt --compute_type=int8 "%%~A")

for %%A in (D:\SubFactory\*.mp4) do (whisperx --language=en --model=tiny --output_dir=D:\SubFactory --output_format=srt --compute_type=int8 "%%~A")
```

**Note 1** - Use one line for each video format that you want to transcribe. Other than a difference for video format (like "mkv" and "mp4"), the lines should be identical. Add lines for other video formats, insofar as necessary.
**Note 2** - In my experience, this only works if this text file is in ANSI encoding (so do not use UTF encoding).

(4) Save the text file with a name like this: `CreateSubtitlesWhisperX-English-tiny.bat.txt`.

(5) Create this subfolder: `C:\StartWhisperX`.

(6) Place a copy of `CreateSubtitlesWhisperX-English-tiny.bat.txt` in `C:\StartWhisperX`. After that, in `C:\StartWhisperX`, remove `.txt` from the file name, so that this file name results: `CreateSubtitlesWhisperX-English-tiny.bat`. (Be sure that file extensions are shown when you do this.)

(7) Open your command-line interface as Administrator, and run this (without quotes): 
`C:\StartWhisperX\CreateSubtitlesWhisperX-English-tiny.bat`

Now you are running a test run with the short test videos that you earlier placed in `D:\SubFactory`. All video files in that folder, will be transcribed now. 

Insofar as necessary, create other text files with similar contents for other models or other languages, e.g. `CreateSubtitlesWhisperX-English-medium.bat.txt`. Place these other files also in C`:\StartWhisperX`, with `.txt` removed.

**Comment by llurk** [comment]
I followed your instructions, and it worked. May I ask how I should install WhisperX to be able to run it on CMD? I have followed the instructions provided by the author of WhisperX to install the WhisperX env on Conda3. Every time I launch WhisperX, I need to activate the env first and then execute WhisperX commands or call WhisperX. but cmd can't, Thanks.

**Comment by oep42** [comment]
This is the comment (in this issue) from yesterday from llurk:
> I followed your instructions, and it worked. May I ask how I should install WhisperX to be able to run it on CMD? I have followed the instructions provided by the author of WhisperX to install the WhisperX env on Conda3. Every time I launch WhisperX, I need to activate the env first and then execute WhisperX commands or call WhisperX. but cmd can't, Thanks.

While I was preparing my response to this comment from llurk from yesterday, it disappeared. Below is my response to this comment anyway.


I don't know Conda. I installed WhisperX without it. Perhaps someone with knowledge of Conda can help.

I do not have the problem of having to activate something every time I launch WhisperX. Below I describe how I installed WhisperX on Windows.


**Preparations before installing WhisperX**


(1) Download the latest Python version 3.10 for your system (e.g. Python 3.10.11) from here: https://www.python.org/downloads/.

(2) Run the Python installer. At the start of this installation, make sure that "Use administrator privileges when installing py.exe" is checked and that "Add python.exe to PATH" is also checked.

(3) Download the latest version of Git from here:
https://git-scm.com/downloads.

(4) Run the Git installer (with the default configuration).

(5) Download and install FFmpeg with the instructions from here:
https://phoenixnap.com/kb/ffmpeg-windows.
**Note** - The "essentials" version of FFmpeg is sufficient for WhisperX.

(6) Open your command-line interface as Administrator, and run the following command:
`pip install --upgrade pip` 

(7) There may be a notice that a new version of pip is available, with instructions on how to upgrade pip. If so, run the upgrade command, which may look like this:
`python.exe -m pip install --upgrade pip`


**Install WhisperX**


Install the latest version of WhisperX with this command:
`pip install git+https://github.com/m-bain/whisperx.git`



**Downgrade (if you would like to do so)**

According to [this](https://github.com/m-bain/whisperX/issues/232), the current version of WhisperX is faster than the previous version, but the quality of its output is not as good as the quality of the output of the previous version. (I did some tests myself, and concluded that the quality of the output of the previous version 2.0.1, is significantly better than that of the current version 3.1.1.) This may be a reason to downgrade to the previous version. Based on [this](https://github.com/m-bain/whisperX/issues/232#issuecomment-1546460436), to downgrade to the previous version, sequentially run the following commands:
```
pip uninstall whisperx
pip install git+https://github.com/m-bain/whisperx.git@v2.0.1
pip uninstall torchaudio
pip install torchaudio==0.13.1
pip uninstall torch
pip3 install torch==1.13.1 --index-url https://download.pytorch.org/whl/cu117 --no-cache-dir
```

**Note 1 when using version 2.0.1** - Do not use the option `--compute_type=int8` with WhisperX version 2.0.1, because that version does not have that option. If this option is being used mistakenly, the processing will stop with this error message: 
`whisperx: error: unrecognized arguments: --compute_type=int8`

**Note 2 when using version 2.0.1** - When using text files like `CreateSubtitlesWhisperX-English-medium.bat.txt` with WhisperX version 2.0.1 (see my earlier comment above), it may be useful to add this line at the beginning of it. 
`for %%A in (D:\SubFactory\*.wav) do (del "%%~A")`
This line will remove, at the start of each new transcription run with WhisperX, any WAV files that may have been left in the `D:\SubFactory` subfolder by a previous run with WhisperX version 2.0.1. (A WAV file is left behind by WhisperX version 2.0.1 from a previous run, either if that run was completed successfully, or if that run was aborted in some way.)
If there has been such a previous run with the `TestVideo1.mp4` video, and there is a new run with `TestVideo1.mp4`, then (if leftover WAV files have not been removed before this run) the processing will stop and this message will appear: 
`File 'D:\SubFactory\TestVideo1.wav' already exists. Overwrite? [y/N]`
By removing leftover WAV files from previous runs at the beginning of a new run, this type of stop in the middle of a transcription run with WhisperX, is avoided. (Unlike WhisperX version 2.0.1, WhisperX version 3.1.1 does not leave any WAV files after a successful run.)


**Upgrade (if you would like to do so)**

Run this command to upgrade to the latest version of WhisperX:
`pip install git+https://github.com/m-bain/whisperx.git --upgrade`

**Comment by llurk** [comment]
Thank you, I followed and it worked. I'm sorry, but I would like to ask for more information about how WhisperX works. When I use WhisperX on my machine, it seems to run purely on Python and the CPU, without any visible impact on the GPU. Is this normal? Additionally, the subtitle output time for each video, which is approximately 2 hours long, takes about 20 minutes (CPU:I7 9800x). Is this also considered normal? Could it be that WhisperX doesn't utilize the GPU because my GPU is outdated (GTX 1080Ti)? Or is there a way to enable GPU support for WhisperX?

**Comment by llurk** [comment]
I ran into a small problem when I downgraded to 2.0.1. Have you ever had this error? Any ideas on how to fix it?

[whisperx_error.txt](https://github.com/m-bain/whisperX/files/11663306/whisperx_error.txt)

**Comment by oep42** [comment]
I have never encountered the error `ModuleNotFoundError: No module named 'pyannote.audio.core'`. I don't know how to fix it. It seems that pyannote is not installed correctly. Perhaps you could search for information on how to install pyannote, or perhaps you could open a new issue.
