### ISSUE TITLE
Is whisperx safe to use when inputting sensitive data inside?

### ISSUE THREAD

**Issue by jake-cohen91c** [m-bain/whisperX#616]
Is there a way to confirm that sensitive data stays securely inside the whisperx workflow fromthe beginning where the whisper model transcribes it all the way to the huggingface pipelines?
I don't see an audit anywhere in the web and would like to know if its safe to use

**Comment by Tux-Panik** [comment]
Hi there,
Interesting question.

> You only need internet to download the models, once downloaded, the whole pipeline can be run offline
> The whisper model runs entirely on your machine and has no ability to transfer data to anywhere by itself

Even when using diarization?
On my end, it crashes when trying to reach HuggingFace.co

Regards,

**Comment by jim60105** [comment]
> Hi there, Interesting question.
> 
> > You only need internet to download the models, once downloaded, the whole pipeline can be run offline
> > The whisper model runs entirely on your machine and has no ability to transfer data to anywhere by itself
> 
> Even when using diarization? On my end, it crashes when trying to reach HuggingFace.co
> 
> Regards,

It is accessing HuggingFace to download the diarization model.  
This model cannot be preloaded in the WhisperX project due to licensing restrictions, which is also why you need to accept the user agreement and input `--hf_token`.

I'm not really sure if it needs to access HuggingFace for verification at the second time execution, but even with this design, I think it's reasonable.

**Comment by Tux-Panik** [comment]
I do confirm that the model must be downloaded at least one time on the local device.

Below, a recorded when not connected on the second time execution:
`WARNING:faster_whisper:An error occured while synchronizing the model Systran/faster-whisper-large-v2 from the Hugging Face Hub:
(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/Systran/faster-whisper-large-v2/revision/main (Caused by ProxyError(\'Unable to connect to proxy\', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x76234ffdb4c0>: Failed to resolve \'[redacted]\' ([Errno -3] Temporary failure in name resolution)")))'), '(Request ID: 69620352-b687-45f3-a959-77b6b7a5916e)')
`

Then precising it will use the local model if it exists:
`
WARNING:faster_whisper:Trying to load the model directly from the local cache, if it exists.
`

Thus, in these conditions it appears to be safe.
Many thanks for clarifications.
