### ISSUE TITLE
Conflicting dependencies ERROR

### ISSUE THREAD

**Issue by urbaaa** [m-bain/whisperX#673]
Hi, I'm not really familiarized with python and codding in general, but I'm trying to solve a problem I have while downloading the clipsai library. When I download it I have this ERROR message coming up, "ERROR: Cannot install clipsai==0.1 and clipsai==0.2.1 because these package versions have conflicting dependencies." 
I've tried creating a virtual environment (venv) but still have the same problem. 

This is the whole error:
_**ERROR: Cannot install clipsai==0.1 and clipsai==0.2.1 because these package versions have conflicting dependencies.**_
_**The conflict is caused by:**_
    **_clipsai 0.2.1 depends on mediapipe_**
    **_clipsai 0.1 depends on mediapipe_**

Thanks!

**Comment by gillens** [comment]
Hi, I think you'll have better luck submitting an issue at the [clipsai repository](https://github.com/ClipsAI/clipsai). As far as I can tell `whisperx` does not use clipsai, rather clipsai uses whisperx.

That said, what commands did you run to set up and get that error? It should be able to be fixed by removing the older version of clipsai (0.1) from the dependencies of your project.

**Comment by Barabazs** [comment]
Closing as off-topic.
