### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by tzhgkm** [m-bain/whisperX#7]
Hi,

I couldn't find align model used for Chinese in "torchaudio.pipelines". Does it support Chinese?

Thanks

**Comment by m-bain** [comment]
Need a wav2vec2.0 model finetuned on chinese.
Seems there are some on huggingface https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn

Currently whisperX doesn't support huggingface pipelines though, when I have the bandwidth I can try add this. Otherwise shouldn't be tricky to add this yourself.

**Comment by m-bain** [comment]
Please see recent commit 
https://github.com/m-bain/whisperX/commit/e909f2f766b23b2000f2d95df41f9b844ac53e49
I tried adding this chinese model but it seems not able to align properly. It's hard for me to see what's happening in the dictionary / alignment because im not familiar with the language. @tzhgkm if you can help here that would be great

**Comment by tzhgkm** [comment]
Thank you!
I changed "zh" to "Chinese" in LANGUAGES_WITHOUT_SPACES, and then added Chinese huggingface model.
It seemed that it worked fine for me.

https://user-images.githubusercontent.com/12479016/208854490-a2d6961a-eebc-4f04-8312-9471018ef0c6.mov

**Comment by mack007liu** [comment]
> huggingface模型

huggingface模型 的地址吗？

**Comment by tzhgkm** [comment]
> > huggingface模型
> 
> huggingface模型 的地址吗？

DEFAULT_ALIGN_MODELS_HF = {
    "ja": "jonatasgrosman/wav2vec2-large-xlsr-53-japanese",
    "Chinese": "jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn",
}

**Comment by m-bain** [comment]
added here (keeping "zh" code) [c6fa7df](https://github.com/m-bain/whisperX/commit/c6fa7df3cc7caae68722363ef0736043f3d75450)
