### ISSUE TITLE
May I ask how C # can use this project

### ISSUE THREAD

**Issue by dfengpo** [m-bain/whisperX#774]
I want to integrate your project into my project,
But I developed using C #.
May I ask how I can request your project? It can also be done through an API format

**Comment by maciejbielecki** [comment]
I did something like this:
```
ProcessStartInfo startInfo = new ProcessStartInfo();
startInfo.CreateNoWindow = true;
startInfo.FileName = "whisperx";
startInfo.Arguments = $"\"{request.FileName}\" {(request.IsCpu ? "--compute_type int8" : "")} --model {request.Model} --language {request.Language}  --output_dir \"{Path.GetFullPath(Path.Combine(outputPath, request.Id.ToString(), "output"))}\" {(request.ShouldTranslate == false ? string.Empty : "--task translate")}";

Process prc = Process.Start(startInfo);
prc.EnableRaisingEvents = true;
await prc.WaitForExitAsync();
```

**Comment by Godfreyid** [comment]
> I did something like this:
> 
> ```
> ProcessStartInfo startInfo = new ProcessStartInfo();
> startInfo.CreateNoWindow = true;
> startInfo.FileName = "whisperx";
> startInfo.Arguments = $"\"{request.FileName}\" {(request.IsCpu ? "--compute_type int8" : "")} --model {request.Model} --language {request.Language}  --output_dir \"{Path.GetFullPath(Path.Combine(outputPath, request.Id.ToString(), "output"))}\" {(request.ShouldTranslate == false ? string.Empty : "--task translate")}";
> 
> Process prc = Process.Start(startInfo);
> prc.EnableRaisingEvents = true;
> await prc.WaitForExitAsync();
> ```
> 
>  [Hide text](#)

Hello @maciejbielecki,
I hope all is well?
I've been wanting to make a small Windows.Forms app with whisperX that would simply take a video/audio file and generate subs when you hit some "Generate Subs" button. I remember this Process() module and its ProcessStartInfo() property business from a while back and thought that would be the quickest way for me to get the app done (since i barely use Python and am thus unfamiliar with its quirks). Anyway, just wanted to ask if this code snippet you provided has worked for you before i set out to build the app?

Kind regards

**Comment by Barabazs** [comment]
This is not the right place to discuss this. Closing as off-topic.
